# This is a basic workflow to help you get started with Actions
name: gambetech_ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.1'

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_name: 'samuel.molu'
          user_email: 'samuel.molu@gambetech.com'
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: master  # default: gh-pages
          cname: gambetech.com
          publish_dir: ./book
